version = 1

[[annotations]]
path = [
    ".gitattributes",
    ".github/**",
    ".gitignore",
    "*.md",
    "REUSE.toml",
    "Dockerfile",
    "build.zig",
    "build.zig.zon",
    "package/**",
    "pkg/**",
    "src/**",
]
SPDX-FileCopyrightText = "Nikolay Govorov"
SPDX-License-Identifier = "AGPL-3.0-or-later"
