name: Build and test application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
          mirror: "https://pkg.earth/zig"

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          update-environment: false

      - name: Check licenses
        run: |
          pip install reuse
          reuse lint

      - name: Lint
        run: |
          zig fmt --ast-check --check .

      - name: Unit tests
        run: |
          zig build test

      - name: Package
        uses: goreleaser/goreleaser-action@v6
        with:
          version: 'latest'
          args: release --snapshot --clean

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            dist/*.apk
            dist/*.deb
            dist/*.rpm
            dist/*.pkg.tar.zst
            dist/checksums.txt

  release:
    name: Update niglty tag
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - name: Update 'nightly' tag
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git tag -f nightly
          git push origin --force tag nightly
